development:
  bucket: vcjsupply_development
  access_key_id: AKIAIG74TRQ7QFQQTFRA
  secret_access_key: 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
test:
  bucket: vcjsupply_test
  access_key_id: AKIAIG74TRQ7QFQQTFRA
  secret_access_key: 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
production:
  bucket: vcjsupply_production
  access_key_id: AKIAIG74TRQ7QFQQTFRA
  secret_access_key: 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